local_backend: true

backend:
  name: git-gateway
  branch: __BRANCH__
  squash_merges: true

display_url: https://www.grzs.si
logo_url: /media/brand/logo.png
media_folder: static/media/uploads
public_folder: /media/uploads

slug:
  encoding: ascii
  clean_accents: true
i18n:
  structure: multiple_files
  locales: [sl, en]

aliases:
  - &TITLE {name: title, label: Title, widget: string, i18n: true}
  - &DRAFT {name: draft, label: Draft, widget: boolean, required: false, i18n: true}
  - &SLUG {name: slug, label: Slug, widget: string, required: false, i18n: true}
  - &URL {name: url, label: URL, widget: string, required: false, i18n: true}
  - &DESCRIPTION {label: Description, name: description, widget: text, i18n: true}
  - &BODY {label: Content, name: body, widget: markdown, i18n: true}
  - &DATE {label: Date, name: date, widget: datetime, i18n: duplicate}
  - &GRS_UNIT {label: GRS Unit, name: unit, widget: string, required: false, i18n: duplicate}
  - &AUTHOR {label: Author, name: author, widget: string, required: false, i18n: true}
  - &TEASER {label: Teaser, name: teaser, widget: string, i18n: true}
  - &TAGS {name: tags, widget: hidden, default: [article], i18n: duplicate}
  - &LAYOUT {name: layout, widget: hidden, default: article, i18n: duplicate}
  - &SHOW_FEATURED {label: Show featured image on page, name: showFeatured, i18n: duplicate, widget: select, options: ['false', 'true']}
  - &FEATURED_IMAGE {label: Featured image, name: image, required: false, i18n: true, widget: object, fields: [
      {label: Source, name: src, widget: image, required: false, i18n: duplicate},
      {label: Text, name: alt, widget: string, required: false, i18n: true},
    ]}
  - &BUTTON {name: button, i18n: true, widget: object, fields: [
      {name: href, widget: string, i18n: true},
      {name: text, widget: string, i18n: true},
    ]}
  - &GALLERY {name: gallery, widget: list, required: false, i18n: true, fields: [
      {label: Image, name: src, widget: image, i18n: duplicate},
      {name: text, widget: string, required: false, i18n: true}
    ]}
  - &PAGE_FIELDS [
      *TITLE,
      *URL,
      *SHOW_FEATURED,
      *FEATURED_IMAGE,
      *BODY,
      *GALLERY,
    ]
  - &HOME_FIELDS [
      *TITLE,
      *DESCRIPTION,
      {label: Gallery 1, name: "swipeGalleryTop", widget: list, fields: [
        {label: Image, name: src, widget: image},
        {name: text, widget: string},
      ]},
      {label: Gallery 2, name: swipeGalleryMiddle, widget: list, fields: [
        {label: Image, name: src, widget: image},
        {name: text, widget: string},
      ]},
      {label: Gallery 3, name: swipeGalleryBottom, widget: list, fields: [
        {label: Image, name: src, widget: image},
        {name: text, widget: string}
      ]},
      {name: help, widget: object, fields: [
        {name: supertitle, widget: string},
        {name: title, widget: string},
        {name: text, widget: text},
        {name: topics, widget: list, fields: [
          {name: title, widget: string},
        ]},
        *BUTTON,
      ]},
      {name: support, widget: object, fields: [
        {name: supertitle, widget: string},
        {name: title, widget: string},
        {name: text, widget: text},
      ]},
      {name: responsibility, widget: object, fields: [
        {name: title, widget: string},
        {name: links, widget: list, fields: [
          {name: title, widget: text},
          {name: desc, widget: text},
          {name: href, widget: string},
        ]},
      ]},
      {name: banner, widget: object, fields: [
        {name: href, widget: string, required: false},
        {name: title, widget: string, required: false},
        {name: srcMobile, label: mobile image, widget: image, required: false},
        {name: srcDesktop, label: destop image, widget: image, required: false},
      ]},
      {name: news, widget: object, fields: [
        {name: supertitle, widget: string, required: false},
        {name: title, widget: string},
        *BUTTON,
      ]},
      {label: Slider, name: exposedContent, allow_add: true, widget: list, required: true, fields: [
        *TITLE,
        {label: Description, name: desc, widget: string},
        {label: Link for button more, name: href, widget: string},
        {label: Order, name: weight, widget: number},
      ]}
    ]
  - &ABOUT_FIELDS [
      {name: foreword, widget: string},
      {label: Title, name: titleText, widget: string},
      *URL,
      *DESCRIPTION,
      *FEATURED_IMAGE,
      *BODY,
      {name: documents, widget: object, fields: [
        *TITLE,
        {name: items, widget: list, fields: [
          *TITLE,
          {label: Description, name: desc, widget: string},
          {label: File, name: src, widget: file},
        ]},
      ]},
    ]
  - &CONTACT_FIELDS [
      *TITLE,
      *URL,
      {name: subtitle, widget: string},
      *DESCRIPTION,
      {name: cards, widget: object, fields: [
        *TITLE,
        {name: grzs, widget: object, fields: [
          {name: name, widget: string},
          {name: address, widget: string},
          {name: post, widget: string},
          {name: map, widget: object, fields: [
            {name: text, widget: string},
            {name: url, widget: string},
          ]},
          {label: EMŠO, name: emso, widget: object, fields: [
            {name: text, widget: string},
            {name: value, widget: string},
          ]},
          {name: vat, widget: object, fields: [
            {name: text, widget: string},
            {name: value, widget: string},
          ]},
          {label: Additional info, name: info, widget: string},
        ]},
        {label: Open hours, name: openHours, widget: object, fields: [
          *TITLE,
          {name: hours, widget: list, fields: [
            {name: name, widget: string},
            {name: value, widget: string},
          ]},
        ]},
        {name: contact, widget: object, fields: [
            {name: phone, widget: string},
            {name: email, widget: string},
        ]},
        {label: "Additional info", name: "infos", widget: list, fields: [
            {name: name, widget: string},
            {name: value, widget: string},
        ]},
        {label: Cta Contact, name: contactCta, widget: object, fields: [
            {name: phone, widget: string},
            {name: email, widget: string},
        ]},
      ]},
      {name: documents, widget: object, fields: [
        *TITLE,
        {name: items, widget: list, fields: [
          {label: Description, name: desc, widget: string},
        ]},
      ]},
    ]
  - &MEDIACENTER_FIELDS [
      *TITLE,
      *URL,
      *DESCRIPTION,
      *FEATURED_IMAGE,
      {name: person, widget: object, fields: [
        *TITLE,
        {name: name, widget: string},
        {name: position, widget: string},
        {name: phone, widget: string},
        {name: email, widget: string},
      ]},
      {name: documents, widget: object, fields: [
        *TITLE,
        {name: items, widget: list, fields: [
          *TITLE,
          {label: Description, name: desc, widget: string},
          {label: File, name: src, widget: file},
        ]},
      ]},
    ]
  - &MENU_ITEM_FIELDS [
      {name: name, widget: string},
      {name: url, widget: string},
      {name: identifier, widget: string, required: false},
      {name: parent, widget: string, required: false},
      {name: weight, widget: number, required: false},
    ]
  - &MENU_FIELDS [
      {name: main, widget: list, label_singular: item, fields: *MENU_ITEM_FIELDS},
      {name: upper, widget: list, label_singular: item, fields: *MENU_ITEM_FIELDS},
      {name: donate, widget: list, label_singular: item, fields: *MENU_ITEM_FIELDS},
    ]
  - &CONDITIONS_FIELDS [
      *TITLE,
      *DRAFT,
      *URL,
      *DESCRIPTION,
      {label: Description Markdown, name: descriptionHTML, widget: markdown, minimal: true},
      *BODY,
    ]

collections:
  - name: novice
    format: yaml-frontmatter
    label: Novice
    label_singular: article (novice)
    folder: content/aktualno/novice
    create: true
    slug: "{{slug}}"
    filter: {field: tags, value: article}
    preview_path: aktualno/novice/{{slug}}
    i18n: true
    editor:
      preview: false
    fields: [
      *TITLE,
      *DRAFT,
      *SLUG,
      {label: Category, name: categories,  widget: select, multiple: true, i18n: duplicate, options: [
        {label: Fotogalerija, value: fotogalerija},
        {label: Novica, value: novica},
        {label: Reševalne akcije, value: resevalne-akcije},
        {label: Dogodki, value: dogodki},
        {label: Video, value: video},
        {label: V spomin, value: v-spomin},
      ]},
      *DATE,
      *GRS_UNIT,
      *AUTHOR,
      *TEASER,
      *DESCRIPTION,
      *FEATURED_IMAGE,
      *BODY,
      *GALLERY,
      *TAGS,
      *LAYOUT,
    ]

  - name: nasveti
    format: yaml-frontmatter
    label: Nasveti
    label_singular: article (nasveti)
    folder: content/resevanje/nasveti-grzs
    create: true
    slug: "{{slug}}"
    filter: {field: tags, value: article}
    preview_path: resevanje/nasveti/{{slug}}
    i18n: true
    editor:
      preview: false
    fields: [
      *TITLE,
      *DRAFT,
      *URL,
      {label: Category, name: tipCategories, widget: select, multiple: true, options: [
        {label: Video, value: video},
        {label: Varno v gore, value: Varno v gore},
      ]},
      *DATE,
      *GRS_UNIT,
      *AUTHOR,
      *TEASER,
      *DESCRIPTION,
      *FEATURED_IMAGE,
      *BODY,
      *GALLERY,
      *TAGS,
      *LAYOUT,
    ]

  - name: medijsko-sredisce
    format: yaml-frontmatter
    label: Medijsko središče
    label_singular: article (medijsko središče)
    folder: "content/medijsko-sredisce"
    create: true
    slug: "{{slug}}"
    filter: {field: tags, value: article}
    preview_path: medijsko-sredisce/{{slug}}
    i18n: true
    editor:
      preview: false
    fields: [
      *TITLE,
      *DRAFT,
      *SLUG,
      *DATE,
      *GRS_UNIT,
      *AUTHOR,
      *TEASER,
      *DESCRIPTION,
      *SHOW_FEATURED,
      *FEATURED_IMAGE,
      *BODY,
      *GALLERY,
      *TAGS,
      *LAYOUT,
    ]

  - label: Pages
    name: pages
    editor:
      preview: false
    files: [
      {label: Domov SL, name: home-sl, file: content/_index.sl.md, fields: *HOME_FIELDS},
      {label: Domov EN, name: home-en, file: content/_index.en.md, fields: *HOME_FIELDS},
      {label: Društva in postaje SL, name: drustva-in-postaje-sl, file: content/o-grzs/drustva-in-postaje.sl.md, fields: *PAGE_FIELDS},
      {label: Društva in postaje EN, name: drustva-in-postaje-en, file: content/o-grzs/drustva-in-postaje.en.md, fields: *PAGE_FIELDS},
      {label: IKAR SL, name: ikar-sl, file: content/o-grzs/ikar-mednarodno-resevanje.sl.md, fields: *PAGE_FIELDS},
      {label: IKAR EN, name: ikar-en, file: content/o-grzs/ikar-mednarodno-resevanje.en.md, fields: *PAGE_FIELDS},
      {label: Sklad Okrešelj SL, name: sklad-okreselj-sl, file: content/o-grzs/sklad-okreselj.sl.md, fields: *PAGE_FIELDS},
      {label: Sklad Okrešelj EN, name: sklad-okreselj-en, file: content/o-grzs/sklad-okreselj.en.md, fields: *PAGE_FIELDS},
      {label: Nameni del dohodnine SL, name: dohodnina-sl, file: content/postani-podpornik/nameni-del-dohodnine.sl.md, fields: *PAGE_FIELDS},
      {label: Nameni del dohodnine EN, name: dohodnina-en, file: content/postani-podpornik/nameni-del-dohodnine.en.md, fields: *PAGE_FIELDS},
      {label: Doniraj SL, name: doniraj-sl, file: content/postani-podpornik/doniraj.sl.md, fields: *PAGE_FIELDS},
      {label: Doniraj EN, name: doniraj-en, file: content/postani-podpornik/doniraj.en.md, fields: *PAGE_FIELDS},
      {label: Pravila in pogoji SL, name: pravila-in-pogoji-sl, file: content/pravila-in-pogoji.sl.md, fields: *PAGE_FIELDS},
      {label: Pravila in pogoji EN, name: pravila-in-pogoji-en, file: content/pravila-in-pogoji.en.md, fields: *PAGE_FIELDS},
      {label: Piskotki SL, name: piskotki-sl, file: content/piskotki.sl.md, fields: *PAGE_FIELDS},
      {label: Piskotki EN, name: piskotki-en, file: content/piskotki.en.md, fields: *PAGE_FIELDS},
      {label: Varstvo osebnih podatkov SL, name: varstvo-osebnih-podatkov-sl, file: content/varstvo-osebnih-podatkov.sl.md, fields: *PAGE_FIELDS},
      {label: Varstvo osebnih podatkov EN, name: varstvo-osebnih-podatkov-en, file: content/varstvo-osebnih-podatkov.en.md, fields: *PAGE_FIELDS},
      {label: Kdo je gorski reševalec SL, name: kdo-je-gorski-resevalec-sl, file: content/resevanje/kdo-je-gorski-resevalec.sl.md, fields: *PAGE_FIELDS},
      {label: Kdo je gorski reševalec EN, name: kdo-je-gorski-resevalec-en, file: content/resevanje/kdo-je-gorski-resevalec.en.md, fields: *PAGE_FIELDS},
      {label: Klic v sili SL, name: klic-v-sili-sl, file: content/resevanje/klic-v-sili.sl.md, fields: *PAGE_FIELDS},
      {label: Klic v sili EN, name: klic-v-sili-en, file: content/resevanje/klic-v-sili.en.md, fields: *PAGE_FIELDS},
      {label: Predstavitev GRZS SL, name: predstavitev-sl, file: content/o-grzs/predstavitev.sl.md, fields: *ABOUT_FIELDS},
      {label: Predstavitev GRZS EN, name: predstavitev-en, file: content/o-grzs/predstavitev.en.md, fields: *ABOUT_FIELDS},
      {label: Kontakt GRZS SL, name: kontakt-sl, file: content/o-grzs/kontakt.sl.md, fields: *CONTACT_FIELDS},
      {label: Kontakt GRZS EN, name: kontakt-en, file: content/o-grzs/kontakt.en.md, fields: *CONTACT_FIELDS},
      {label: Media center SL, name: media-center-sl, file: content/medijsko-sredisce/_index.sl.md, fields: *MEDIACENTER_FIELDS},
      {label: Media center EN, name: media-center-en, file: content/medijsko-sredisce/_index.en.md, fields: *MEDIACENTER_FIELDS},
      {label: Aktualne razmere SL, name: conditions-sl, file: content/aktualno/razmere.sl.md, fields: *CONDITIONS_FIELDS},
      {label: Aktualne razmere EN, name: conditions-en, file: content/aktualno/razmere.en.md, fields: *CONDITIONS_FIELDS},
    ]

  - name: components
    label: Components
    i18n:
      structure: single_file
    editor:
      preview: false
    files: [
      {label: Card 112, name: card112, file: data/card112.json, i18n: true, fields: [
        *TITLE,
        {label: Call Button, name: callButton, widget: object, i18n: true, fields: [
          {name: text, widget: string, i18n: true},
          {label: Link, name: src, widget: string, i18n: true},
        ]},
        {label: Foreign texts, name: "foreign", widget: object, i18n: true, fields: [
          {label: Austria, name: at, widget: string, i18n: true},
          {label: Italija, name: it, widget: string, i18n: true},
          {label: Hrvaška, name: hr, widget: string, i18n: true},
          {label: Madžarska, name: h, widget: string, i18n: true},
        ]},
      ]},
      {label: Partners, name: partners, file: data/partners.json, i18n: true, fields: [
        {name: supertitle, widget: string, i18n: true},
        *TITLE,
        {name: items, widget: list, i18n: true, fields: [
          {name: title, widget: string, i18n: true},
          {name: image, widget: image, i18n: duplicate},
        ]},
      ]},
      {label: Partners Similar, name: partners-similar, file: data/partnersSimilar.json, i18n: true, fields: [
        {name: supertitle, widget: string, i18n: true},
        *TITLE,
        {name: items, widget: list, i18n: true, fields: [
          {name: title, widget: string, i18n: true},
          {name: image, widget: image, i18n: duplicate},
          {name: href, widget: string, i18n: duplicate},
        ]},
      ]},
      {label: Newsletter, name: newsletter, file: data/newsletter.json, i18n: true, fields: [
        {name: supertitle, widget: string, i18n: true},
        *TITLE,
        {name: success, widget: text, i18n: true},
        {name: email, widget: string, i18n: true},
        {name: submit, widget: string, i18n: true},
        {name: error, widget: string, i18n: true},
        {name: emailError, widget: string, i18n: true},
        {name: terms, widget: text, i18n: true},
        {name: required, widget: string, i18n: true},
      ]},
      {label: Footer, name: footer, file: data/footer.json, i18n: true, fields: [
        {name: copyright, widget: string, i18n: true},
        {name: social, widgets: list, i18n: true, fields: [
          {name: href, widget: string, i18n: true},
          {name: icon, widget: string, i18n: duplicate},
          {name: title, widget: string, i18n: true},
        ]},
        *BUTTON,
        {name: legal, widgets: list, i18n: true, fields: [
          {name: href, widget: string, i18n: true},
          {name: title, widget: string, i18n: true},
        ]},
      ]},
    ]

  - name: general
    label: General
    editor:
      preview: false
    files: [
      {label: Menus SL, name: menus-sl, file: config/_default/menus.sl.json, fields: *MENU_FIELDS},
      {label: Menus EN, name: menus-en, file: config/_default/menus.en.json, fields: *MENU_FIELDS},
    ]
